trigger:
  branches:
    include:
      - master  # Change this to your main branch

jobs:
- job: Build_and_Deploy
  displayName: 'Build and Deploy Drupal'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'

  - script: |
      # Install dependencies
      sudo apt-get update
      sudo apt-get install -y zip php composer

      # Install Drupal dependencies using Composer
      cd .
      composer install --no-dev --optimize-autoloader

      # Zip Drupal application
      zip -r drupal_app.zip .

  - task: CopyFiles@2
    inputs:
      SourceFolder: '.'
      Contents: '**/*.zip'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drupal_package'
      publishLocation: 'Container'

- job: Deploy_to_CyberPanel  # No dependency needed anymore
  displayName: 'Deploy to CyberPanel'
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Build_and_Deploy

  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'drupal_package'
      downloadPath: '$(System.ArtifactsDirectory)'
   
  - task: FtpUpload@2
    inputs:
      credentialsOption: 'inputs'
      serverUrl: 'server-url'
      username: 'username'
      password: 'pwd'
      rootDirectory: '$(System.ArtifactsDirectory)'
      filePatterns: '**'
      remoteDirectory: '/public_html'
      clean: true
      preservePaths: true
      trustSSL: true
