name: Deploy Drupal to CyberPanel

on:
  push:
    branches:
      - master  # Change this to your main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install dependencies and zip Drupal application
      run: |
        sudo apt-get update
        sudo apt-get install -y zip composer
        # cd ./web
        # composer install --no-dev --optimize-autoloader
        zip -r drupal_app.zip .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: drupal_app.zip
        path: ${{ github.workspace }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: drupal_app.zip

    - name: Extract Artifact
      run: |
        unzip ${{ github.workspace }}/drupal_app.zip -d ${{ github.workspace }}/drupal

    - name: FTP Upload
      uses: dennisameling/ftp-upload-action@v1
      with:
        server: ${{ secrets.CYBERPANEL_SERVER }}
        username: ${{ secrets.CYBERPANEL_USERNAME }}
        password: ${{ secrets.CYBERPANEL_PASSWORD }}
        secure: false
        local_dir: ${{ github.workspace }}/drupal/
        server_dir: /public_html/
