name: Deploy Drupal to CyberPanel

on:
  push:
    branches:
      - master  # Change this to your main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install dependencies and zip Drupal application
      run: |
        sudo apt-get update
        sudo apt-get install -y zip composer
        # cd ./web
        # composer install --no-dev --optimize-autoloader
        zip -r drupal_app.zip .

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: drupal_package
        path: ./web/drupal_app.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: drupal_package

    - name: Extract Artifact
      run: |
        unzip ${{ github.workspace }}/drupal_package -d ${{ github.workspace }}/drupal

    - name: FTP Upload
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.CYBERPANEL_SERVER }}
        username: ${{ secrets.CYBERPANEL_USERNAME }}
        password: ${{ secrets.CYBERPANEL_PASSWORD }}
        local-dir: ${{ github.workspace }}/drupal
        remote-dir: /public_html
